/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroSection;
  featuredPost?: FeaturedPostSection;
  recentPosts?: RecentPostsSection;
  popularPosts?: PopularPostsSection;
};

export type PopularPostsSection = {
  _type: "popularPostsSection";
  label?: string;
  ctaButton?: CtaButton;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type RecentPostsSection = {
  _type: "recentPostsSection";
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
};

export type FeaturedPostSection = {
  _type: "featuredPostSection";
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
};

export type HeroSection = {
  _type: "heroSection";
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
};

export type CtaButton = {
  _type: "ctaButton";
  label?: string;
  href?: string;
  openInNewTab?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CustomImage = {
  _type: "customImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  href?: string;
};

export type LogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "logo";
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: LogoReference;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  copyrightText?: string;
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: LogoReference;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  ctaButton?: CtaButton;
};

export type Logo = {
  _id: string;
  _type: "logo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: CustomImage;
  logoText?: string;
  logoLink?: string;
};

export type Quote = {
  _type: "quote";
  text?: string;
  author?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HomePage
  | PopularPostsSection
  | BlogReference
  | RecentPostsSection
  | FeaturedPostSection
  | HeroSection
  | CtaButton
  | SanityImageAssetReference
  | CustomImage
  | SocialLink
  | LogoReference
  | Footer
  | Newsletter
  | NavLink
  | Navbar
  | Logo
  | Quote
  | Blog
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/nav-bar-query.ts
// Variable: NAV_BAR_QUERY
// Query: *[_type=="navbar"]{_id,logo->{logo{asset,alt},logoText,logoLink},navLinks,ctaButton}
export type NAV_BAR_QUERY_RESULT = Array<{
  _id: string;
  logo: {
    logo: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    logoText: string | null;
    logoLink: string | null;
  } | null;
  navLinks: Array<
    {
      _key: string;
    } & NavLink
  > | null;
  ctaButton: CtaButton | null;
}>;

// Source: src/sanity/queries/newsletter-query.ts
// Variable: NEWSLETTER_QUERY
// Query: *[_type=="newsletter"]{_id,title,description}
export type NEWSLETTER_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="navbar"]{_id,logo->{logo{asset,alt},logoText,logoLink},navLinks,ctaButton}': NAV_BAR_QUERY_RESULT;
    '*[_type=="newsletter"]{_id,title,description}': NEWSLETTER_QUERY_RESULT;
  }
}
