/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type GenericSection = {
  _type: "genericSection";
  id?: string;
  label?: string;
  title?: string;
  body?: string;
  layoutType?: "hero" | "splitImageRight" | "splitImageLeft" | "textBlock";
  mainImage?: CustomImage;
  ctaLabel?: string;
  ctaLink?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  slug?: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & FeaturedPostSection)
    | ({
        _key: string;
      } & PopularPostsSection)
    | ({
        _key: string;
      } & RecentPostsSection)
    | ({
        _key: string;
      } & BlogSection)
    | ({
        _key: string;
      } & BlogCardSection)
    | ({
        _key: string;
      } & GenericSection)
    | ({
        _key: string;
      } & HowWeWorkSection)
    | ({
        _key: string;
      } & ImageSection)
    | ({
        _key: string;
      } & HeaderSection)
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CustomImage = {
  _type: "customImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HeaderSection = {
  _type: "headerSection";
  id?: string;
  label?: string;
  title?: string;
  description?: string;
};

export type ImageSection = {
  _type: "imageSection";
  id?: string;
  displayImage?: CustomImage;
};

export type TextCard = {
  _type: "textCard";
  label?: string;
  title?: string;
  description?: string;
  button?: CtaButton;
};

export type HowWeWorkSection = {
  _type: "howWeWorkSection";
  id?: string;
  label?: string;
  title?: string;
  description?: string;
  cards?: Array<
    {
      _key: string;
    } & TextCard
  >;
};

export type CtaButton = {
  _type: "ctaButton";
  label?: string;
  href?: string;
  openInNewTab?: boolean;
};

export type BlogCardSection = {
  _type: "blogCardSection";
  id?: string;
  label?: string;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type BlogSection = {
  _type: "blogSection";
  id?: string;
  label?: string;
  blog?: BlogReference;
};

export type FeaturedPostSection = {
  _type: "featuredPostSection";
  id?: string;
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
};

export type PopularPostsSection = {
  _type: "popularPostsSection";
  id?: string;
  label?: string;
  ctaButton?: CtaButton;
  postCount?: number;
};

export type RecentPostsSection = {
  _type: "recentPostsSection";
  id?: string;
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
  postCount?: number;
};

export type HeroSection = {
  _type: "heroSection";
  id?: string;
  label?: string;
  featuredImage?: CustomImage;
  blog?: BlogReference;
  ctaButton?: CtaButton;
};

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  href?: string;
};

export type LogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "logo";
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: LogoReference;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  copyrightText?: string;
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  logo?: LogoReference;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  ctaButton?: CtaButton;
};

export type Logo = {
  _id: string;
  _type: "logo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: CustomImage;
  logoText?: string;
  logoLink?: string;
};

export type Quote = {
  _type: "quote";
  text?: string;
  author?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | GenericSection
  | Page
  | SanityImageAssetReference
  | CustomImage
  | Slug
  | HeaderSection
  | ImageSection
  | TextCard
  | HowWeWorkSection
  | CtaButton
  | BlogCardSection
  | BlogReference
  | BlogSection
  | FeaturedPostSection
  | PopularPostsSection
  | RecentPostsSection
  | HeroSection
  | SocialLink
  | LogoReference
  | Footer
  | Newsletter
  | NavLink
  | Navbar
  | Logo
  | Quote
  | Blog
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/blog-query.ts
// Variable: BLOGS_QUERY
// Query: *[_type=="blog"]|order(createdAt desc)[$start...$end]
export type BLOGS_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular?: boolean;
  body?: Array<
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  >;
}>;

// Source: src/sanity/queries/blog-query.ts
// Variable: BLOG_QUERY
// Query: *[_type=="blog" && slug.current==$slug][0]
export type BLOG_QUERY_RESULT = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular?: boolean;
  body?: Array<
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  >;
} | null;

// Source: src/sanity/queries/nav-bar-query.ts
// Variable: NAV_BAR_QUERY
// Query: *[_type=="navbar"]{_id,logo->{logo{asset,alt},logoText,logoLink},navLinks,ctaButton}
export type NAV_BAR_QUERY_RESULT = Array<{
  _id: string;
  logo: {
    logo: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    logoText: string | null;
    logoLink: string | null;
  } | null;
  navLinks: Array<
    {
      _key: string;
    } & NavLink
  > | null;
  ctaButton: CtaButton | null;
}>;

// Source: src/sanity/queries/newsletter-query.ts
// Variable: NEWSLETTER_QUERY
// Query: *[_type=="newsletter"]{_id,title,description}
export type NEWSLETTER_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  description: string | null;
}>;

// Source: src/sanity/queries/page-query.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    label,    sections[]{      ...,      blog->    }  }
export type PAGE_QUERY_RESULT = {
  label: string | null;
  sections: Array<
    | {
        _key: string;
        _type: "blogCardSection";
        id?: string;
        label?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "blogSection";
        id?: string;
        label?: string;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
      }
    | {
        _key: string;
        _type: "featuredPostSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "genericSection";
        id?: string;
        label?: string;
        title?: string;
        body?: string;
        layoutType?:
          "hero" | "splitImageLeft" | "splitImageRight" | "textBlock";
        mainImage?: CustomImage;
        ctaLabel?: string;
        ctaLink?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "headerSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "howWeWorkSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & TextCard
        >;
        blog: null;
      }
    | {
        _key: string;
        _type: "imageSection";
        id?: string;
        displayImage?: CustomImage;
        blog: null;
      }
    | {
        _key: string;
        _type: "popularPostsSection";
        id?: string;
        label?: string;
        ctaButton?: CtaButton;
        postCount?: number;
        blog: null;
      }
    | {
        _key: string;
        _type: "recentPostsSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
        postCount?: number;
      }
  > | null;
} | null;

// Source: src/sanity/queries/page-query.ts
// Variable: BLOGS_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "blog"][0]{    label,    sections[]{      ...,      blog->    }  }
export type BLOGS_PAGE_QUERY_RESULT = {
  label: string | null;
  sections: Array<
    | {
        _key: string;
        _type: "blogCardSection";
        id?: string;
        label?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "blogSection";
        id?: string;
        label?: string;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
      }
    | {
        _key: string;
        _type: "featuredPostSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "genericSection";
        id?: string;
        label?: string;
        title?: string;
        body?: string;
        layoutType?:
          "hero" | "splitImageLeft" | "splitImageRight" | "textBlock";
        mainImage?: CustomImage;
        ctaLabel?: string;
        ctaLink?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "headerSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "howWeWorkSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & TextCard
        >;
        blog: null;
      }
    | {
        _key: string;
        _type: "imageSection";
        id?: string;
        displayImage?: CustomImage;
        blog: null;
      }
    | {
        _key: string;
        _type: "popularPostsSection";
        id?: string;
        label?: string;
        ctaButton?: CtaButton;
        postCount?: number;
        blog: null;
      }
    | {
        _key: string;
        _type: "recentPostsSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
        postCount?: number;
      }
  > | null;
} | null;

// Source: src/sanity/queries/page-query.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_type == "page" && slug.current == "blog/"][0]{    label,    sections[]{      ...,      blog->    }  }
export type BLOG_PAGE_QUERY_RESULT = {
  label: string | null;
  sections: Array<
    | {
        _key: string;
        _type: "blogCardSection";
        id?: string;
        label?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "blogSection";
        id?: string;
        label?: string;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
      }
    | {
        _key: string;
        _type: "featuredPostSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "genericSection";
        id?: string;
        label?: string;
        title?: string;
        body?: string;
        layoutType?:
          "hero" | "splitImageLeft" | "splitImageRight" | "textBlock";
        mainImage?: CustomImage;
        ctaLabel?: string;
        ctaLink?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "headerSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        blog: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
      }
    | {
        _key: string;
        _type: "howWeWorkSection";
        id?: string;
        label?: string;
        title?: string;
        description?: string;
        cards?: Array<
          {
            _key: string;
          } & TextCard
        >;
        blog: null;
      }
    | {
        _key: string;
        _type: "imageSection";
        id?: string;
        displayImage?: CustomImage;
        blog: null;
      }
    | {
        _key: string;
        _type: "popularPostsSection";
        id?: string;
        label?: string;
        ctaButton?: CtaButton;
        postCount?: number;
        blog: null;
      }
    | {
        _key: string;
        _type: "recentPostsSection";
        id?: string;
        label?: string;
        featuredImage?: CustomImage;
        blog: {
          _id: string;
          _type: "blog";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          slug?: Slug;
          category?: string;
          createdAt?: string;
          excerpt?: string;
          heroImage?: CustomImage;
          cardImage?: CustomImage;
          isFeatured?: boolean;
          isPopular?: boolean;
          body?: Array<
            | ({
                _key: string;
              } & CustomImage)
            | ({
                _key: string;
              } & Quote)
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
          >;
        } | null;
        ctaButton?: CtaButton;
        postCount?: number;
      }
  > | null;
} | null;

// Source: src/sanity/queries/popular-post-query.ts
// Variable: POPULAR_POST_QUERY
// Query: *[_type=="blog" && isPopular==true]|order(createdAt desc)
export type POPULAR_POST_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular: true;
  body?: Array<
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  >;
}>;

// Source: src/sanity/queries/recent-post-query.ts
// Variable: RECENT_POST_QUERY
// Query: *[_type=="blog" && isPopular == false]|order(createdAt desc)
export type RECENT_POST_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  createdAt?: string;
  excerpt?: string;
  heroImage?: CustomImage;
  cardImage?: CustomImage;
  isFeatured?: boolean;
  isPopular: false;
  body?: Array<
    | ({
        _key: string;
      } & CustomImage)
    | ({
        _key: string;
      } & Quote)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  >;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="blog"]|order(createdAt desc)[$start...$end]': BLOGS_QUERY_RESULT;
    '*[_type=="blog" && slug.current==$slug][0]': BLOG_QUERY_RESULT;
    '*[_type=="navbar"]{_id,logo->{logo{asset,alt},logoText,logoLink},navLinks,ctaButton}': NAV_BAR_QUERY_RESULT;
    '*[_type=="newsletter"]{_id,title,description}': NEWSLETTER_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n    label,\n    sections[]{\n      ...,\n      blog->\n    }\n  }': PAGE_QUERY_RESULT;
    '*[_type == "page" && slug.current == "blog"][0]{\n    label,\n    sections[]{\n      ...,\n      blog->\n    }\n  }': BLOGS_PAGE_QUERY_RESULT;
    '*[_type == "page" && slug.current == "blog/"][0]{\n    label,\n    sections[]{\n      ...,\n      blog->\n    }\n  }': BLOG_PAGE_QUERY_RESULT;
    '*[_type=="blog" && isPopular==true]|order(createdAt desc)': POPULAR_POST_QUERY_RESULT;
    '*[_type=="blog" && isPopular == false]|order(createdAt desc)': RECENT_POST_QUERY_RESULT;
  }
}
