import type { Metadata } from "next";
import {Roboto, Raleway } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ooter";
import NavBar from "@/components/nav-bar";
import NewsletterForm from "@/components/newsletter-form";



const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100","400", "500", "600", "700"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className="min-h-full m- bg-[#FAFAFA]">
        <NavBar />
        {children}
        <NewsletterForm />
        <Footer />
      </body>
    </html>
  );
}
